/**
 * EventManagement.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateEventDto } from '../model/models';
import { RegistrationDto } from '../model/models';
import { UpdateEventDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    eventsGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    eventsIdGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param updateEventDto 
     */
    eventsIdPut(id: string, updateEventDto?: UpdateEventDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param registrationDto 
     */
    eventsIdRegisterDelete(id: string, registrationDto?: RegistrationDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param registrationDto 
     */
    eventsIdRegisterPost(id: string, registrationDto?: RegistrationDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createEventDto 
     */
    eventsPost(createEventDto?: CreateEventDto, extraHttpRequestParams?: any): Observable<{}>;

}
